### ISSUE TITLE
kubectl image bug with bash: applet not found

### ISSUE THREAD

**Issue by tuananh** [chainguard-images/images#467] opened 2023-04-17 04:33 UTC
### Which image/versions are related to this issue/feature request?

image version: latest@sha256:2e570b2d17bdcc9e21f4ab791f3e6085af29df479e49a200ea7104899d339434

### Issue/Feature description

the command to test

```
docker run -it --rm --entrypoint bash cgr.dev/chainguard/kubectl:latest@sha256:2e570b2d17bdcc9e21f4ab791f3e6085af29df479e49a200ea7104899d339434
```

got the following error
```
bash: applet not found
```

`sh` works fine though.

**Comment by patflynn** [comment] 2023-04-17 15:06
@tuananh this is WAI by the looks of the config.  Do you think the busybox shell is not enough for the likely usecases?

**Comment by tuananh** [comment] 2023-04-18 07:36
In my case, sh is enough but why was a bash symlink was created in the first place?

**Comment by patflynn** [comment] 2023-04-18 13:47
@kaniini

**Comment by imjasonh** [comment] 2023-04-30 17:23
@dlorenc was this fixed by the busybox-full package now being available? Should we switch to use that so bash is provided?

**Comment by dlorenc** [comment] 2023-04-30 17:39
No, but @deitch is working on another fix here to only create the correct symlinks

**Comment by deitch** [comment] 2023-04-30 18:19
This merged in 3 days ago via [this](https://github.com/chainguard-dev/apko/pull/640). However, it only works if busybox is of a version that includes `/etc/busybox-paths.d/`. 

The issue highlighted here is two-fold:

* it is trying to execute `bash`, which does not exist on the image
* It should get "no such file", as `/bin/bash` should not exist.

busybox does not appear to include bash. So executing bash never should work. However, if that is the case, then the symlink should not exist, rather than having the `applet: not found` error. That, specifically, is what the fix linked to above addresses.

**Comment by imjasonh** [comment] 2023-04-30 20:07
It sounds like this is working as intended; busybox does not provide bash.

There are improvements we can make to the error message but fundamentally this shouldn't work. Is that right?

**Closed** 2023-04-30 20:07 UTC
Labels: needs-triage
